apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: miniprojekti-boilerplate

resources:
  - manifests/configmap.yaml
  - manifests/imagestream.yaml
  - manifests/service.yaml
  - manifests/route.yaml
  - manifests/volumeclaim.yaml
  - manifests/deployment.yaml

secretGenerator:
  - name: secret
    envs:
      - secret.env

configurations:
  - manifests/kustomizeconfig.yaml

images:
  - name: source-image
    newName: ghcr.io/mluukkai/ohtu-boilerplate
    newTag: latest

patches:
  - target:
      kind: Route
      name: route
    patch: |-
      - op: add
        path: /spec/host
        value: route-miniprojekti-boilerplate.ext.okd-cs-test-0.k8s.cs.helsinki.fi
