apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ohtuprojekti-staging

resources:
  - configmap.yaml
  - imagestream.yaml
  - service.yaml
  - route.yaml
  - volumeclaim.yaml
  - deployment.yaml

secretGenerator:
  - name: secret
    literals:
      - SECRET_KEY=a52c5a7977873164135603da8aa0052cef2f2299acf7c22d65a64e060830ed26

configurations:
  - kustomizeconfig.yaml

images:
  - name: source-image
    newName: ghcr.io/mluukkai/ohtu-boilerplate
    newTag: latest

patches:
  - target:
      kind: Route
      name: route
    patch: |-
      - op: add
        path: /spec/host
        value: miniprojekti-ohtuprojekti-staging.ext.ocp-test-0.k8s.it.helsinki.fi
